# Generated by Django 4.0.2 on 2022-02-24 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('MemberId', models.AutoField(primary_key=True, serialize=False)),
                ('MemberName', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('ProjectId', models.AutoField(primary_key=True, serialize=False)),
                ('ProjectName', models.CharField(max_length=500)),
                ('CreatedAt', models.DateField()),
                ('HasDeadline', models.BooleanField()),
                ('DeadlineDate', models.DateField()),
            ],
        ),
    ]
